### ISSUE TITLE
aws-sso time fails

### ISSUE THREAD

**Issue by hesstobi** [synfinatic/aws-sso-cli#1008]
**Output of `aws-sso version`:**
```
Example output:
AWS SSO CLI Version 1.17.0 -- Copyright 2021-2024 Aaron Turner
Homebrew (1.17.0) built at 2024-07-10T21:26:18Z
```

**Describe the bug:**
The command `aws-sso time` does print the time for the Token expiration. Instead
`FATAL   Unable to parse 2024-07-25T14:36:37+02:00: parsing time "2024-07-25T14:36:37+02:00" as "2006-01-02 15:04:05 -0700 MST": cannot parse "T14:36:37+02:00" as " "` is printed and the command fails.

**To Reproduce:**
 1. aws-sso time

**Expected behavior:**
The command prints the time for the Token expiration, e.g. `59m`

**Desktop (please complete the following information):**
 - OS: ubunut
 - Version 20.04.6 LTS

**Additional context:**
This may be related to https://github.com/synfinatic/aws-sso-cli/commit/8eae16e1e26f0f434033a67ceab81c9de625305b

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    ek:
        SSORegion: eu-central-1
        StartUrl: https://someurl.awsapps.com/start
        DefaultRegion: eu-central-1


DefaultRegion: eu-central-1
ConsoleDuration: 180
CacheRefresh: 168
AutoConfigCheck: true
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
# Wsl settings
Browser: /usr/bin/wslview
SecureStore: pass
```
