### ISSUE TITLE
Default container for SSO Device Flow

### ISSUE THREAD

**Issue by Moulick** [synfinatic/aws-sso-cli#1015]
**Is your feature request related to a problem? Please describe.**

When using `UrlAction: open-url-in-container`, and when "aws-sso-cli" authenticates against AWS, it open the AWS SSO approval page in the `Default` container. I usually have my AWS SSO account logged in directly in firefox and not in any container. This causes me to either have to login to AWS in the default container again or at-least manually open a new tab and copy paste the URL (https://device.sso.eu-central-1.amazonaws.com/?user_code=abcd-xyz) outside of the `Default` container

**Describe the solution you'd like**
Do not open the initial device.sso.eu-central-1.amazonaws.com inside the `Default` container when `UrlAction: open-url-in-container` is configured. Or make the container name configurable?

**Describe alternatives you've considered**
The firefox multi container plugin as far as I understand does not support forcing opening website outside of the containers, only force opening inside a particular container. So I don't have any workaround.

**Comment by synfinatic** [comment]
Have you tried [AuthUrlAction](https://synfinatic.github.io/aws-sso-cli/latest/config/#authurlaction)?

**Comment by Moulick** [comment]
> Have you tried [AuthUrlAction](https://synfinatic.github.io/aws-sso-cli/latest/config/#authurlaction)?

Tried now, it still tries to open the link in a container of the name of the AWS SSO. For example with the below settings, it tries to open it in container `hello` 


```yaml
DefaultRegion: eu-central-1
ConsoleDuration: 720
CacheRefresh: 36
AutoConfigCheck: true
AuthUrlAction: open
UrlAction: open-url-in-container
UrlExecCommand:
  - /Applications/Firefox.app/Contents/MacOS/firefox
  - "%s"
ConfigProfilesUrlAction: open
LogLevel: warn
HistoryLimit: 100
FullTextSearch: true

ConfigVariables:
  sts_regional_endpoints: regional

ProfileFormat: "{{ FirstItem .AccountName (.AccountAlias | nospace) }}:{{ .RoleName }}"

AccountPrimaryTag:
  - env

ListFields:
  - AccountName
  - Profile
  - AccountAlias
  - AccountIdPad
  # - Arn
  - Expires
  - RoleName

SSOConfig:
  hello:
    SSORegion: eu-central-1
    StartUrl: <redacted>
    DefaultRegion: eu-central-1
    maxbackoff: 0
    maxretry: 0
    Accounts:
```

**Comment by synfinatic** [comment]
Sorry, `AuthUrlAction` is specific to your `SSOConfig` block.  Guess I should make that more clear in the docs.

```yaml
SSOConfig:
    hello:
        AuthUrlAction: open
```
