### ISSUE TITLE
Firefox Performs Search Instead of Opening in Container Tab

### ISSUE THREAD

**Issue by aesanch2** [synfinatic/aws-sso-cli#1021]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.17.0 -- Copyright 2021-2024 Aaron Turner
Homebrew (1.17.0) built at 2024-07-10T21:26:18Z
```

**Describe the bug:**
When using `open-url-in-container` for `UrlAction` for Firefox with Multi-Account Containers, Firefox will not open the tab in a new container and instead sends the url to the search bar and performs a search.

**To Reproduce:**
 1. Install [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) addon in Firefox
 2. Set Firefox as default browser
 3. Set `UrlAction` to `open-url-in-container` in `~/.aws-sso/config.yaml`.
 4. Set `UrlExecCommand` to the following:
```
UrlExecCommand:
    - /Applications/Firefox.app/Contents/MacOS/firefox
    - "%s"
```
 5. Run `aws-sso console` and select an account/role to open the console in a new container tab

**Expected behavior:**
A new container tab for the selected AWS Account is opened in Firefox.

**Screenshots:**
<img width="1081" alt="image" src="https://github.com/user-attachments/assets/beea01e5-5861-421a-a044-42280b352c6c">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.5

**Additional context:**
References to an optional `open-url-in-firefox-container` are made [in this issue](https://github.com/synfinatic/aws-sso-cli/issues/760#issuecomment-1890832813), but that doesn't appear to be an option any longer.

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    Default:
        SSORegion: us-east-1
        StartUrl: https://xxx.awsapps.com/start
        AuthUrlAction: open
DefaultSSO: Default
DefaultRegion: us-east-1
ConsoleDuration: 720
CacheRefresh: 168
Threads: 5
MaxBackoff: 5
MaxRetry: 10
UrlAction: open-url-in-container
UrlExecCommand:
    - /Applications/Firefox.app/Contents/MacOS/firefox
    - "%s"
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ .AccountIdPad }}:{{ .RoleName }}"
AccountPrimaryTag:
    - AccountName
    - AccountAlias
    - Email
PromptColors:
    descriptionbgcolor: Turquoise
    descriptiontextcolor: Black
    inputbgcolor: DefaultColor
    inputtextcolor: DefaultColor
    prefixbackgroundcolor: DefaultColor
    prefixtextcolor: Blue
    previewsuggestionbgcolor: DefaultColor
    previewsuggestiontextcolor: Green
    scrollbarbgcolor: Cyan
    scrollbarthumbcolor: LightGrey
    selecteddescriptionbgcolor: DarkGray
    selecteddescriptiontextcolor: White
    selectedsuggestionbgcolor: DarkGray
    selectedsuggestiontextcolor: White
    suggestionbgcolor: Cyan
    suggestiontextcolor: White
ListFields:
    - AccountIdPad
    - AccountAlias
    - RoleName
    - Profile
    - Expires
FullTextSearch: true

```
