### ISSUE TITLE
panic when running `aws-sso ecs server`

### ISSUE THREAD

**Issue by fabian-braun** [synfinatic/aws-sso-cli#1040]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.17.0 -- Copyright 2021-2024 Aaron Turner
Homebrew (1.17.0) built at 2024-07-10T21:26:18Z
```

**Describe the bug:**
When invoking `aws-sso ecs server` on a fresh zsh, it panics.

**To Reproduce:**

```
> aws-sso ecs server
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x101343aac]

goroutine 1 [running]:
main.(*EcsServerCmd).Run(0x0?, 0x14000388060)
        github.com/synfinatic/aws-sso-cli/cmd/aws-sso/ecs_server_cmd.go:72 +0x1cc
reflect.Value.call({0x1014fa8c0?, 0x14000306c70?, 0x140005519a8?}, {0x101352890, 0x4}, {0x1400000e9a8, 0x1, 0x101278be8?})
        reflect/value.go:596 +0x970
reflect.Value.Call({0x1014fa8c0?, 0x14000306c70?, 0x14000551aa8?}, {0x1400000e9a8?, 0x1015e0600?, 0x140005519e0?})
        reflect/value.go:380 +0x94
github.com/alecthomas/kong.callFunction({0x1014fa8c0?, 0x14000306c70?, 0x14000551c30?}, 0x14000388180)
        github.com/alecthomas/kong@v0.9.0/callbacks.go:98 +0x390
github.com/alecthomas/kong.(*Context).RunNode(0x14000112680, 0x1400030f860, {0x14000551eb0, 0x1, 0x14000344e20?})
        github.com/alecthomas/kong@v0.9.0/context.go:774 +0x630
github.com/alecthomas/kong.(*Context).Run(0x0?, {0x14000551eb0?, 0x14000277de8?, 0x1013390bc?})
        github.com/alecthomas/kong@v0.9.0/context.go:799 +0x138
main.main()
        github.com/synfinatic/aws-sso-cli/cmd/aws-sso/main.go:171 +0x530
```

**Expected behavior:**
The credential server should be started.

**Screenshots:**

I assume this happens because `ctx.Store` is used before it gets initialised.

<img width="741" alt="Screenshot 2024-08-26 at 13 57 07" src="https://github.com/user-attachments/assets/99623a82-186b-463f-b233-cfbe47c454d4">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 14.6.1
 - Chip: Apple M1 Pro

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    moia:
        SSORegion: eu-central-1
        StartUrl: https://moia-dev.awsapps.com/start
        DefaultRegion: eu-central-1
DefaultRegion: eu-central-1
ConsoleDuration: 60
CacheRefresh: 48
AutoConfigCheck: true
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 100
HistoryMinutes: 1440
ProfileFormat: "{{ .AccountAlias }}"
```
