### ISSUE TITLE
DefaultRegion not being correctly set for Account or Role config when using interactive menu UI

### ISSUE THREAD

**Issue by steven-meunier-lu** [synfinatic/aws-sso-cli#1075]
**Output of `aws-sso version`:**
```
Example output:
AWS SSO CLI Version 1.17.0 -- Copyright 2021-2024 Aaron Turner
Homebrew (1.17.0) built at 2024-07-10T21:26:18Z
```

**Describe the bug:**
The DefaultRegion is not being correctly set when the DefaultRegion is specified in the config file at the Account or Role level, when using the interactive text menu UI. This problem only occurs when using `aws-sso exec` with the interactive menu. When using `aws-sso-profile`, `aws-sso list`, or `aws-sso exec --account 123456789012 --role Foo` then the DefaultRegion is correctly set.

I have tracked the bug down to https://github.com/synfinatic/aws-sso-cli/blob/4d823e0d129e4d9b007352afc43779eec4aa52ed/cmd/aws-sso/exec_cmd.go#L82 Changing this to
`region := ctx.Settings.GetDefaultRegion(accountid, role, ctx.Cli.Exec.NoRegion)`
fixes the problem. Since the user is using the interactive menu, `ctx.Cli.Exec.AccountId` and `ctx.Cli.Exec.Role` have not been set. I'm not sure if this is the preferred fix but am happy to submit an PR with this change if you think this is the right fix for this.

**To Reproduce:**
Assume a config similar to the following:
```
SSOConfig:
    Default:
      Accounts:
          123456789012:
              DefaultRegion: eu-west-1
```

 1. Run `aws-sso exec`
 2. Use the menu to select account 123456789012 and the role
 3. AWS_SSO_DEFAULT_REGION and AWS_DEFAULT_REGION is set to 'us-east-1' instead of 'eu-west-1'
 

**Expected behavior:**
AWS_SSO_DEFAULT_REGION and AWS_DEFAULT_REGION should be set to 'eu-west-1'
 
**Screenshots:**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Version [e.g. 10.15.5]

**Additional context:**

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    Default:
      Accounts:
          123456789012:
              DefaultRegion: eu-west-1
```
