### ISSUE TITLE
Ignore env vars for nested executions. 

### ISSUE THREAD

**Issue by monwolf** [synfinatic/aws-sso-cli#1095]
Hi! 
I'm using aws-sso with helm to access a s3 chart repo, and aws-sso for connecting EKS. 

So I have to run helm with the env AWS_ACCESS_KEY_ID and it calls aws-sso for doing eks login.
I'm using a kube config global with this configuration for the login:

```yaml
- name: arn:aws:eks:eu-west-1:xxxx:cluster/xx-devops-xxx-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - exec
      - -A
      - "xxxxxx"
      - --role=AdministratorAccess
      - aws
      - eks
      - get-token
      - --cluster-name
      - ae-devops-eks-cluster
      command: aws-sso
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

So when helm run its it shows the error:

```
error="Conflicting environment variable 'AWS_ACCESS_KEY_ID' is set"
```

I tried to empty the env var as follows:
```yaml
      - name: AWS_ACCESS_KEY_ID
        value:
```
But the same error happens. 

How would you be able to solve this?  Is there any way to ignore the env vars without doing a wrapper for this command?
