### ISSUE TITLE
Can't assume an IAM role that isn't defined by SSO

### ISSUE THREAD

**Issue by liamdawson** [synfinatic/aws-sso-cli#1202]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.17.0 -- Copyright 2021-2024 Aaron Turner
Homebrew (1.17.0) built at 2024-07-10T21:26:18Z
```

**Describe the bug:**
If I define a role which isn't in SSO, and provide role-chaining step through `Via`, `aws-sso` still considers it an "invalid profile".

**To Reproduce:**
 1. Create an IAM role `MyManualRole` by hand in an account
 2. Add that role and define the `Via` property for it (see contents below)
 3. Run `aws-sso exec --profile=123456789012:MyManualRole`

**Expected behavior:**

`aws-sso exec --profile=123456789012:MyManualRole` will start a shell session with credentials for `MyManualRole` instead of writing
```
FATAL   Invalid --profile 123456789012:MyManualRole
```

`aws-sso config-profiles --print` will include a profile for `MyManualRole`, instead of writing
```
WARNING config.yaml has arn:aws:iam::123456789012:role/MyManualRole but you don't have access
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 15.4.1

**Contents of `~/.config/aws-sso/config.yaml`:**
```
SSOConfig:
    Default:
        Accounts:
            123456789012:
                Roles:
                    MySSORole: {}
                    MyManualRole:
                        Via: arn:aws:iam::123456789012:role/MySSORole
```
