### ISSUE TITLE
I just installed aws-sso-cli and I got `unexpected argument config`

### ISSUE THREAD

**Issue by alexmolas** [synfinatic/aws-sso-cli#1212]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 2.0.0 -- Copyright 2021-2025 Aaron Turner
Homebrew (2.0.0) built at 2025-05-11T01:17:22Z
```

**Describe the bug:**
I installed `aws-sso-cli` via brew (ie: `brew install aws-sso-cli`) in my MacBook, and when running `aws-sso config` I get the following error

```
aws-sso: error: unexpected argument config
```

**To Reproduce:**
 1. `aws-sso config`

**Expected behavior:**
Being able to configure my account.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Sequoia (15.4.1)

**Contents of `~/.aws-sso/config.yaml`:**

```
SSOConfig:
    Default:
        SSORegion: us-east-1
        StartUrl: <>
ConsoleDuration: 720
CacheRefresh: 168
UrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ FirstItem .AccountName (.AccountAlias | nospace) }}:{{ .RoleName }}"
FullTextSearch: true
```
