### ISSUE TITLE
Unable to refresh cache / Session token not found or invalid

### ISSUE THREAD

**Issue by rgarrigue** [synfinatic/aws-sso-cli#279]
**Output of `aws-sso version`:**

Tried both

```
AWS SSO CLI Version 1.7.0 -- Copyright 2021-2022 Aaron Turner
c3a5f4106f55baadacf83cd43788c1b85b07bce9 (v1.7.0) built at 2022-01-09T11:41:18-0800

AWS SSO CLI Version 1.7.1 -- Copyright 2021-2022 Aaron Turner
13a896d2e0d545835813f57d4a2f4a3a11222c61 (v1.7.1) built at 2022-01-16T15:28:49-0800
```

**Describe the bug:**

I've a bunch of aliases to switch between the accounts. It worked fine until yesterday, now it gives the below error

```
aws-sso -L trace eval --sts-refresh --account 101XXXXXXXXXX35 --role Admin              
FATAL   Unable to refresh cache                       error="Unable to get AWS SSO accounts: : Session token not found or invalid\n\tstatus code: 401, request id: "
```

I tried the option that could make sense like sts refresh, not to avail

**Expected behavior:**

As usual, silently switching from account to account

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 21.10

**Contents of `~/.aws-sso/config.yaml`:**
```yaml
---
SSOConfig:
  GS:
    SSORegion: eu-central-1
    StartUrl: https://gs.awsapps.com/start
    DefaultRegion: eu-central-1
DefaultSSO: GS
Browser: chromium
UrlAction: open
LogLevel: warn
HistoryLimit: 100
HistoryMinutes: 1440
ProfileFormat: '{{ FirstItem .AccountName .AccountAlias | StringReplace " " "_" }}_{{ .RoleName }}'
```
