### ISSUE TITLE
Unable to use `aws-sso process`

### ISSUE THREAD

**Issue by kevcube** [synfinatic/aws-sso-cli#286]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.7.2 -- Copyright 2021-2022 Aaron Turner
f589777ef77fb5b847eae209b2cbcc1bdec58a00 (Homebrew) built at 2022-02-09T21:49:30+0000
```

**Describe the bug:**
Unable to run aws-sso process.. I've run aws-sso config, my `~/.aws/config` file is updated, I'm able to use all the other commands of the `aws-sso` tool, but process fails with ...
```
❯ /opt/homebrew/bin/aws-sso -u open -S "ACCOUNT" process --arn arn:aws:iam::010101010101:role/AWSOrganizationsFullAccess
FATAL   Error running command: Please specify --arn or --account and --role
```

I've also tried it when passing the `-a` flag for ARN, `--account` and `--role`, all give the same output.

My log level is set to `debug` and that `FATAL` is the only line of output I get.

**To Reproduce:**
 1. `aws-sso process` with any configuration of flags
 2. I have also tried with the command set as `credential_process` in my `~/.aws/config`, and the results are the same when calling `terragrunt` with `AWS_PROFILE` set.

**Expected behavior:**
spits out creds to stdout when calling raw process? not really sure how it SHOULD work.

**Desktop (please complete the following information):**
 - OS: macOS 12.2 (21D49) (arm64)

**Additional context:**

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
  SIA:
    SSORegion: us-east-2
    StartUrl: https://d-redacted.awsapps.com/start
    DefaultRegion: us-east-2
DefaultSSO: SIA
UrlAction: open
LogLevel: debug
SecureStore: keychain
ConsoleDuration: 360
HistoryLimit: 10
HistoryMinutes: 1440
```
