### ISSUE TITLE
Account numbers with leading zeros cause config parsing failures

### ISSUE THREAD

**Issue by mbainter** [synfinatic/aws-sso-cli#292]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.7.3 -- Copyright 2021-2022 Aaron Turner
9520f708c985cc8015e2d0b2f7781261ef5f1664 (v1.7.3) built at 2022-02-10T08:16:36-0800
```

**Describe the bug:**
When account identifiers start with two zeros the yaml importer misunderstands the intent of the value. It looks like the leading zeros cause it to assume it's an octal value instead of an int. 

**To Reproduce:**
 1. Setup an aws-sso config.yml like so:
 ```yaml
 ---
 SSOConfig:
  Default:
    SSORegion: us-east-1
    StartUrl: https://XXXXXXXX.awsapps.com/start
    Accounts:
      0012345678912:
      Name: MyTestName
```
 2. run any aws-sso command

**Expected behavior:**
It should parse the yaml file correctly

**Screenshots:**
What you actually get is:
```
FATAL   Unable to process config file: 1 error(s) decoding:

* cannot parse 'SSOConfig[Default].Accounts[1.2345678912e+10]' as int: strconv.ParseInt: parsing "1.2345678912e+10": invalid syntax 
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu 21
