### ISSUE TITLE
FATAL  Invalid selection: Too many roles match selected values.

### ISSUE THREAD

**Issue by pulberg** [synfinatic/aws-sso-cli#298]
**Output of `aws-sso version`:**
```
➜ aws-sso version
AWS SSO CLI Version 1.7.4 -- Copyright 2021-2022 Aaron Turner
465eaafbcb29ea217e587a592ec5692937a3f176 (Homebrew) built at 2022-03-07T16:11:43+0000
```

**Describe the bug:**
Cannot select AccountAlias, AccountID, Email, or Role

**To Reproduce:**
 1. aws-sso exec
 2. try to select any option
 3. get error - FATAL   Invalid selection: Too many roles match selected values.

**Expected behavior:**
I am able to select from one of the available options

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS
 - Version [e.g. 10.15.5] 12.2.1

**Additional context:**

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
  Default:
    SSORegion: us-east-2
    StartUrl: https://xxxxxxx.awsapps.com/start
    DefaultRegion: us-east-2
DefaultSSO: Default
UrlAction: open
LogLevel: debug
HistoryLimit: 100
HistoryMinutes: 1440
```
