### ISSUE TITLE
AWS_SSO_FILE_PASSPHRASE not being respected in container

### ISSUE THREAD

**Issue by kevcube** [synfinatic/aws-sso-cli#300]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.7.4 -- Copyright 2021-2022 Aaron Turner
465eaafbcb29ea217e587a592ec5692937a3f176 (v1.7.4) built at 2022-02-25T19:35:25-0800
```

**Describe the bug:**
Docker container built with linux/arm64 alpine:edge and aws-sso 1.7.4 is not respecting AWS_SSO_FILE_PASSPHRASE

**To Reproduce:**
```
~ # echo $AWS_SSO_FILE_PASSPHRASE
test
~ # aws-sso exec
Please use `exit` or `Ctrl-D` to quit.
> AccountAlias Audit
Enter passphrase to unlock /root/.aws-sso/secure: 
FATAL   Aborting with empty password                 
```

If I enter `fdasdffasdfa` as the password, or anything incorrect, it still successfully unlocks the file. If I enter nothing, it fails with `FATAL   Aborting with empty password`

**Expected behavior:**
`aws-sso` silently unlocks the file when the passphrase variable is set.

**Desktop (please complete the following information):**
 - OS: docker alpine edge
 - Version..
 ```
 ~ # uname -a
Linux 3fe4888ff5e6 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 Linux
```

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
  tenant:
    SSORegion: us-east-2
    StartUrl: https://d-redacted.awsapps.com/start
    DefaultRegion: us-east-2
DefaultSSO: tenant
UrlAction: print 
LogLevel: warn
ConsoleDuration: 360
HistoryLimit: 10
HistoryMinutes: 1440
```
