### ISSUE TITLE
Lost contact with keyring

### ISSUE THREAD

**Issue by rgarrigue** [synfinatic/aws-sso-cli#304]
**Output of `aws-sso version`:**

Started with

```
AWS SSO CLI Version 1.7.2 -- Copyright 2021-2022 Aaron Turner
f589777ef77fb5b847eae209b2cbcc1bdec58a00 (v1.7.2) built at 2022-02-05T10:51:23-0800
```

Latest didn't fixed it 

```
AWS SSO CLI Version 1.7.4 -- Copyright 2021-2022 Aaron Turner
465eaafbcb29ea217e587a592ec5692937a3f176 (v1.7.4) built at 2022-02-25T19:35:25-0800
```

**Describe the bug:**

It worked. Then it doesn't. Not sure how it broke, it's most likely my Ubuntu's keyring going wild somehow. I'll post a comment if it work after reboot. But though you'ld like to know.

```
~ ᐅ aws-sso
List of AWS roles for SSO Instance: GoStudent
AccountId    | AccountAlias    | Role                   | Expires
=================================================================
101476298835 | Product DEV     | Admin                  | 4h 0m  
213897467017 | Product PROD    | Admin                  | 2h 4m  
428037846224 | Product DEVOPS  | Admin                  |        

~ ᐅ eval $(aws-sso eval --account 101476298835 --role Admin)

# seahorse prompt to create a new aws-sso-cli keyring

ERROR   Unable to save RegisterClientData             error="L’interface «\u00a0org.freedesktop.DBus.Properties\u00a0» n’existe pas pour l’objet à l’emplacement /"

# clic on the web page's allow

ERROR   Unable to save CreateTokenResponse            error="L’interface «\u00a0org.freedesktop.DBus.Properties\u00a0» n’existe pas pour l’objet à l’emplacement /"
WARNING Unable to cache role credentials in secure store  error="L’interface «\u00a0org.freedesktop.DBus.Properties\u00a0» n’existe pas pour l’objet à l’emplacement /"
```

"nexiste pas pour l'objet à l'emplacement" translate to "doesn't exist for the object at"

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 21.04

**Contents of `~/.aws-sso/config.yaml`:**
```yaml
---
SSOConfig:
  GoStudent:
    SSORegion: eu-central-1
    StartUrl: https://company.awsapps.com/start
    DefaultRegion: eu-central-1
DefaultSSO: Company
Browser: chromium
UrlAction: open
LogLevel: warn
HistoryLimit: 100
HistoryMinutes: 1440
ProfileFormat: '{{ FirstItem .AccountName .AccountAlias | StringReplace " " "_" }}_{{ .RoleName }}'
```
