### ISSUE TITLE
Error output "Too few fields for (role arn) History Tag: '' " when using an account with one role.

### ISSUE THREAD

**Issue by kevcube** [synfinatic/aws-sso-cli#305]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.7.4 -- Copyright 2021-2022 Aaron Turner
465eaafbcb29ea217e587a592ec5692937a3f176 (Homebrew) built at 2022-03-01T15:55:54+0000
```

**Describe the bug:**
when using a role that is the only role on that account, history item is saved with too few tags

```
❯ aws-sso version
ERRO[0000] Too few fields for arn:aws:iam::aws_account_id_redacted:role/AWSAdministratorAccess History Tag: '' 
ERRO[0000] Too few fields for arn:aws:iam::aws_account_id_redacted:role/AWSAdministratorAccess History Tag: '' 
ERROR   Too few fields for arn:aws:iam::aws_account_id_redacted:role/AWSAdministratorAccess History Tag: '' 
AWS SSO CLI Version 1.7.4 -- Copyright 2021-2022 Aaron Turner
465eaafbcb29ea217e587a592ec5692937a3f176 (Homebrew) built at 2022-03-01T15:55:54+0000
```

**To Reproduce:**
 1. Gain access to a SINGLE role on an account
 2. `aws-sso exec`
 3. in selector, choose `> AccountAlias ThisIsTheAccount` and press enter
 4. auth is successful, you get your `exec` shell, but subsequent `aws-sso` calls will spit out error

 **Expected behavior:**
* no error (maybe warning)
* maybe drop-from-history after first error occurrence
* proper add-to-history functionality

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.3

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
  Tenant:
    SSORegion: us-east-2
    StartUrl: https://d-redacted.awsapps.com/start
    DefaultRegion: us-east-2
DefaultSSO: Tenant
UrlAction: print 
LogLevel: warn
ConsoleDuration: 360
HistoryLimit: 10
HistoryMinutes: 1440
```
