### ISSUE TITLE
Wincred not support more than 2600 bytes

### ISSUE THREAD

**Issue by monwolf** [synfinatic/aws-sso-cli#308]
Hi, 

I'm opening this issue because¡ I tried to update from v to v1.7.4 and I saw windows support is broken due to a limitation on the wincred manager.  When I try to run the newer version I'm  getting the error:

```
level=warning msg="Unable to cache role credentials in secure store" func=main.GetRoleCredentials file="/Users/aturner/go/src/github.com/synfinatic/aws-sso-cli/cmd/main.go:280" error="El fragmento ha recibido datos incorrectos."
```

After searching a bit on the Internet I saw the issue: 

https://github.com/danieljoos/wincred/issues/18

That is related to this error message, so I debugged the application and saw the JSON we are trying to save has around 3.7K bytes. 

**To Reproduce:**
aws-sso exec -A "my-account" --role=AdministratorAccess aws  eks get-token --cluster-name my-cluster

**Expected behavior:**

I expect all work fine :) 

**Screenshots:**

Error:

![image](https://user-images.githubusercontent.com/1116133/159794032-654ec065-af5b-413e-a865-f15f41e67fe2.png)

Cause:
![image](https://user-images.githubusercontent.com/1116133/159793856-f9b0b3ef-9fed-4b9a-9ad1-7b9fdc562f80.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context:**
https://github.com/danieljoos/wincred/issues/18

**Contents of `~/.aws-sso/config.yaml`:**

```
SSOConfig:
    xxxx-sso:
        SSORegion: us-east-1
        StartUrl: https://xxxxx.awsapps.com/start
DefaultSSO: xxxx-sso
LogLevel: warn
LogLines: true
UrlAction: open
SecureStore: wincred 
```
