### ISSUE TITLE
AWS Console Sign-In Expiration shows this project URL, not SSO Administrator URL

### ISSUE THREAD

**Issue by guildencrantz** [synfinatic/aws-sso-cli#328]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.7.5 -- Copyright 2021-2022 Aaron Turner
```

**Describe the bug:**
Yesterday I successfully used `aws-sso console`, but today when I went to open a new console window I was greated with the following error in my browser:

```
Amazon Web Services Sign In
Your session has expired. To start a new session, click the link provided by your administrator:
https://github.com/synfinatic/aws-sso-cli To logout, click [here](https://signin.aws.amazon.com/oauth?Action=logout&redirect_uri=https://aws.amazon.com)
```

**To Reproduce:**
 1. `aws-sso console`
 2. Wait for the session to time out
 3. In the browser open a new https://console.aws.amazon.com

**Expected behavior:**
The error should still show up, however the administrator provided link shouldn't go to this project.

**Screenshots:**
![Screen Shot 2022-04-14 at 09 56 10](https://user-images.githubusercontent.com/65403/163430058-cc51f615-39b0-4cc5-99e9-26e2ad95cadd.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 11.6.5

**Additional context:**
 - Browser: Brave
 - Version: V1.37.113

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
  ControlTowerDev:
    SSORegion: us-east-1
    StartUrl: https://d-906766e422.awsapps.com/start
  PFPT:
    SSORegion: us-east-1
    StartUrl: https://d-90676a1dc9.awsapps.com/start
DefaultSSO: PFPT
UrlAction: open
LogLevel: warn
HistoryLimit: 10
HistoryMinutes: 1440
```
