### ISSUE TITLE
Multiple SSO sessions support

### ISSUE THREAD

**Issue by patdohere** [synfinatic/aws-sso-cli#374]
Use case:
- Organization has separate accounts for privileged access for example a Dev account and Prod account.
- The Dev account allows RW roles to Dev accounts and R roles to Prod accounts
- The Prod account allows RW roles to both Dev and Prod accounts

Issue:
- AWS SSO CLI reuses the same SSO session token regardless of config resulting in the need to flush and reauthenticate in order to support multiple SSO sessions

Ideas:
- Map credentials for SSOConfig to seperate session tokens
- In order to support multiple authentication configure seperate UrlAction to authenticate each SSOConfig

**Comment by patdohere** [comment]
```
SSOConfig:
  Dev:
    SSORegion: us-east-2
    StartUrl: https://d-xxxxxxxxxx.awsapps.com/start
    DefaultRegion: us-east-2
  Prod:
    SSORegion: us-east-2
    StartUrl: https://d-xxxxxxxxxx.awsapps.com/start
    DefaultRegion: us-east-2

DefaultRegion: us-east-1
DefaultSSO: Dev

UrlAction: exec
UrlExecCommand:
  - /Applications/Firefox.app/Contents/MacOS/firefox
  - "-private"
  - "%s"
```

The Dev and Prod have identical SSO configs, just different authentications to gain access to different roles
