### ISSUE TITLE
Autocompletion (tab) wonky behavior on WSL ubuntu + oh-my-zsh

### ISSUE THREAD

**Issue by adam-makowski** [synfinatic/aws-sso-cli#426]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.9.2 -- Copyright 2021-2022 Aaron Turner
307f13eb377284001a3545ea1394c2303786925f (v1.9.2) built at 2022-05-13T17:07:59-0700
```

**Describe the bug:**
Hi,
Using tab completion with oh-my-zsh results in aws-sso-cli prompts showing up on each "Tab" key press, rather than after executing any of the sso commands. Tried to source the issue but without any luck so far. 

**To Reproduce:**
 1. Start writing anything and press Tab to autocomplete
 2. Instead of autocompletion results, aws-sso commands helper pops up

**Expected behavior:**
Autocompletion working normally and aws-sso-cli pop ups only when executing aws-sso-cli commands

**Screenshots:**
![image](https://user-images.githubusercontent.com/97021059/193051323-cc3a280d-cce9-4c33-9594-1b6a9d6f7aa1.png)

then, on pressing Tab:
![image](https://user-images.githubusercontent.com/97021059/193051441-f6b52d64-573d-4eb0-afaf-a73913cc646e.png)

**Desktop (please complete the following information):**
 - OS: WSL2 Ubuntu
 - Version 18.04

**Additional context:**
Tried disabling all of the plugins in zshrc, disabling fzf, didnt help as well. Funnily enough, using autocomplete for previously finished sentences (so right arrow for example) works ok. Only tabbing is broken

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    <redacted>:
        SSORegion: eu-north-1
        StartUrl: <redacted>
        DefaultRegion: eu-north-1
DefaultSSO: <redacted>
DefaultRegion: eu-north-1
ConsoleDuration: 720
CacheRefresh: 168
AutoConfigCheck: true
UrlAction: open-url-in-container
ConfigProfilesUrlAction: open-url-in-container
UrlExecCommand:
    - /mnt/c/Program Files/Mozilla Firefox/firefox.exe
    - "%s"
LogLevel: info
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ .AccountId }}:{{ .RoleName }}"
AccountPrimaryTag:
    - AccountName
    - AccountAlias
    - Email
PromptColors:
    descriptionbgcolor: Turquoise
    descriptiontextcolor: Black
    inputbgcolor: DefaultColor
    inputtextcolor: DefaultColor
    prefixbackgroundcolor: DefaultColor
    prefixtextcolor: Blue
    previewsuggestionbgcolor: DefaultColor
    previewsuggestiontextcolor: Green
    scrollbarbgcolor: Cyan
    scrollbarthumbcolor: LightGrey
    selecteddescriptionbgcolor: DarkGray
    selecteddescriptiontextcolor: White
    selectedsuggestionbgcolor: DarkGray
    selectedsuggestiontextcolor: White
    suggestionbgcolor: Cyan
    suggestiontextcolor: White
ListFields:
    - AccountId
    - AccountAlias
    - RoleName
    - Profile
    - ExpiresStr
```
