### ISSUE TITLE
Wrong formatting of StartUrl in config file

### ISSUE THREAD

**Issue by n13k77** [synfinatic/aws-sso-cli#434]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.9.4 -- Copyright 2021-2022 Aaron Turner
f6b9b90d559de3c935000a9acf02be6aa554fb63 (v1.9.4) built at 2022-09-29T13:35:31-0700
```

**Describe the bug:**
After running `aws-sso config`, the `awsapps.com` section in the StartUrl gets duplicated.

**To Reproduce:**
 1. aws-sso config
 2. ✔ SSO Instance Name (DefaultSSO): test
 3. ✔ SSO Start URL Hostname (XXXXXXX.awsapps.com): test|
INFO    Using test.awsapps.com                       

**Expected behavior:**
I expected the StartUrl to be test.awsapps.com, but it shows up in the config as test.awsapps.com.awsapps.com

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04.4

**Additional context:**
https://github.com/synfinatic/aws-sso-cli/blob/v1.9.4/cmd/aws-sso/setup_cmd.go#L110

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    test:
        SSORegion: eu-central-1
        StartUrl: https://test.awsapps.com.awsapps.com/start
        DefaultRegion: eu-central-1
DefaultRegion: eu-central-1
ConsoleDuration: 60
CacheRefresh: 168
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
```
I think the error got introduced here: https://github.com/synfinatic/aws-sso-cli/blob/v1.9.4/cmd/aws-sso/setup_cmd.go#L110
