### ISSUE TITLE
Initial setup fails with 

### ISSUE THREAD

**Issue by joshcyphersonos** [synfinatic/aws-sso-cli#442]
**Output of `aws-sso version`:**

```
AWS SSO CLI Version 1.9.4 -- Copyright 2021-2022 Aaron Turner
f6b9b90d559de3c935000a9acf02be6aa554fb63 (Homebrew) built at 2022-10-19T18:15:49+0000
```

**Describe the bug:**

Since [this commit](https://github.com/synfinatic/aws-sso-cli/commit/8fc2fa137a53cf487f7d0305e8ebd8e464252286) When running the config for the first time, the startUrl is being populated incorrectly. 

It is adding an extra `.awsapps.com` to the url. ex. https://my-url.awsapps.com.awsapps.com/start

**To Reproduce:**
 1. aws-sso config
 2. fill in all required info, including a valid StartUrl.

**Expected behavior:**

The config should populate the startUrl with a valid Url

**Screenshots:**
```
**********************************************************************
* Do you have questions?  Do you like reading docs?  We've got docs! *
* https://github.com/synfinatic/aws-sso-cli/blob/main/docs/config.md *
**********************************************************************

✔ SSO Instance Name (DefaultSSO): DefaultSSO

✔ SSO Start URL Hostname (XXXXXXX.awsapps.com): pd-sonos
✔ SSO Start URL Hostname (XXXXXXX.awsapps.com): pd-sonos
INFO    Using pd-sonos.awsapps.com                   

✔ AWS SSO Region (SSORegion): us-east-1

✔ Default region for connecting to AWS services (DefaultRegion): us-east-1

✔ Hours between AWS SSO cache refresh. 0 to disable. (CacheRefresh): 168

✔ Auto update ~/.aws/config with latest AWS SSO roles? (AutoConfigCheck) Yes

✔ Default action to take with URLs (UrlAction): Open in (default) browser

✔ How to open URLs via $AWS_PROFILE? (ConfigProfilesUrlAction) Open in (default) browser

✔ Specify path to browser to use. Leave empty to use system default (Browser): 

✔ Minutes before AWS Console sessions expire (ConsoleDuration): 60

✔ Maximum number of History items to keep (HistoryLimit): 10
✔ Number of minutes to keep items in History (HistoryMinutes): |1440
✔ Number of minutes to keep items in History (HistoryMinutes
✔ Log Level (LogLevel): error

Awesome!  Saving the new /Users/username/.aws-sso/config.yaml
FATAL   Unable to authenticate                        error="Unable to start device authorization with AWS SSO: operation error SSO OIDC: StartDeviceAuthorization, https response error StatusCode: 400, RequestID: 01c87687-14f0-42a2-b2c9-19c31bcf1fd8, InvalidRequestException: "
```

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version 12.6 (21G115)

**Additional context:**

**Contents of `~/.aws-sso/config.yaml`:**

```
SSOConfig:
    Default:
        SSORegion: us-east-1
        StartUrl: https://my-url.awsapps.com.awsapps.com/start
        DefaultRegion: us-east-1
DefaultRegion: us-east-1
ConsoleDuration: 60
CacheRefresh: 168
AutoConfigCheck: true
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
```
