### ISSUE TITLE
Config profiles dose not use the full AWS account id

### ISSUE THREAD

**Issue by mfroembgen** [synfinatic/aws-sso-cli#446]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.9.4 -- Copyright 2021-2022 Aaron Turner
f6b9b90d559de3c935000a9acf02be6aa554fb63 (Homebrew) built at 2022-11-09T14:24:50+0000
```

**Describe the bug:**
Ignores zeros at the start of the AWS account id for the profile name.

**To Reproduce:**
 1. aws-sso config-profiles

**Expected behavior:**
For consistency, it should have the whole AWS account id inside the profile name.

**Screenshots:**
![CleanShot 2022-11-21 at 10 50 24](https://user-images.githubusercontent.com/23717573/203019737-a9f7d0ab-a132-4ef9-9ec1-ea5a81f5ef3a.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.0.1

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    test:
        SSORegion: eu-central-1
        StartUrl: https://d-000000000.awsapps.com/start
        DefaultRegion: eu-central-1
DefaultRegion: eu-central-1
ConsoleDuration: 60
CacheRefresh: 168
AutoConfigCheck: true
UrlAction: granted-containers
ConfigProfilesUrlAction: granted-containers
UrlExecCommand:
    - /Applications/Firefox.app/Contents/MacOS/firefox
    - "%s"
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
PromptColors:
    SuggestionBGColor: DarkGrey
```
