### ISSUE TITLE
Invalid grant provided

### ISSUE THREAD

**Issue by jeremysimmons** [synfinatic/aws-sso-cli#453]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.9.6 -- Copyright 2021-2022 Aaron Turner
c3208fd25e1f57a77f3d3d9f2b48158ce5c4cef2 (v1.9.6) built at 2022-12-04T17:18:20+0000
```

**Describe the bug:**
During configuration, browser opens and sign-in is attempted, but receive message "invalid_grant Invalid grant provided" on page https://DOMAIN.awsapps.com/start/user-consent/authorize.html?clientId=...&clientType=...&deviceContextId=...&region=us-east-2&state=...

**To Reproduce:**
```
aws-sso config
aws-sso
```
**Expected behavior:**
Signs in and captures available Roles

**Screenshots:**
![image](https://user-images.githubusercontent.com/1406886/206216208-4f399f0a-08d3-4747-9c3d-60631a4dd47d.png)

**Desktop (please complete the following information):**
Microsoft Windows Version 10.0.22621.819

**Additional context:**
Using GSuite for SSO authentication

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    DefaultSSO:
        SSORegion: us-east-1
        StartUrl: https://prosperops.awsapps.com/start
        DefaultRegion: us-east-1
DefaultSSO: DefaultSSO
DefaultRegion: us-east-2
ConsoleDuration: 60
CacheRefresh: 168
Threads: 5
AutoConfigCheck: true
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ AccountIdStr .AccountId }}:{{ .RoleName }}"
AccountPrimaryTag:
    - AccountName
    - AccountAlias
    - Email
PromptColors:
    descriptionbgcolor: Turquoise
    descriptiontextcolor: Black
    inputbgcolor: DefaultColor
    inputtextcolor: DefaultColor
    prefixbackgroundcolor: DefaultColor
    prefixtextcolor: Blue
    previewsuggestionbgcolor: DefaultColor
    previewsuggestiontextcolor: Green
    scrollbarbgcolor: Cyan
    scrollbarthumbcolor: LightGrey
    selecteddescriptionbgcolor: DarkGray
    selecteddescriptiontextcolor: White
    selectedsuggestionbgcolor: DarkGray
    selectedsuggestiontextcolor: White
    suggestionbgcolor: Cyan
    suggestiontextcolor: White
ListFields:
    - AccountId
    - AccountAlias
    - RoleName
    - Profile
    - ExpiresStr
```
