### ISSUE TITLE
Default / override region is not added to the config

### ISSUE THREAD

**Issue by viraptor** [synfinatic/aws-sso-cli#481]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.9.10 -- Copyright 2021-2022 Aaron Turner
unknown (nixpkgs) built at unknown
```

**Describe the bug:**
The configuration for the default region does not seem to be applied to the aws config.

**To Reproduce:**
Current config:
```
SSOConfig:
  Default:
    SSORegion: us-east-1
    StartUrl: ...
    DefaultRegion: us-east-1
    Accounts:
      "718...":
        DefaultRegion: eu-west-1
DefaultRegion: us-east-1
...
```

Config generated with `aws-sso config-profiles` does not include the default region settings.
`aws-vault exec ... -- aws ec2` complains about missing `AWS_REGION`.

**Expected behavior:**
Expected the `region = ...` setting to be added to my generated `.aws/config.yaml` file. 

**Desktop (please complete the following information):**
 - OS: macOS / nixpkgs
 - Version Ventura / nixpkgs-23.05

**Additional context:**
