### ISSUE TITLE
Hitting rate limit with large number of accounts

### ISSUE THREAD

**Issue by ahembree** [synfinatic/aws-sso-cli#520]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.11.0 -- Copyright 2021-2022 Aaron Turner
ea15d31f496ce9e7c13bb76c562a738748bfac47 (v1.11.0) built at 2023-08-03T02:44:01+0000
```

**Describe the bug:**
Receiving `HTTP 429` rate limit errors when attempting to run `aws-sso exec` or `aws-sso cache`.

**To Reproduce:**
 1. `aws-sso exec` or `aws-sso flush -t all && aws-sso cache` to force authentication in browser
 2. Click "Allow" in browser
 3. Go in continuous loop of clicking "Allow" in another new tab and seeing 429 errors in CLI (every time it encounters a 429, it opens another new tab to click "Allow")
 4. Eventually it works after about 5 times of clicking "Allow"

**Expected behavior:**
Present list of accounts and roles normally to obtain CLI creds for with no 429 errors

**Screenshots:**
![image](https://github.com/synfinatic/aws-sso-cli/assets/8049680/d901827f-a4cf-4dc9-b315-b279f0c13b72)

**Desktop (please complete the following information):**
 - OS: macOS (M1 Pro chip)
 - Version 13.5

**Additional context:**
I have access to a large number of accounts, about 50, and only people that have access to the same number are encountering the issue, others with access to a much smaller amount do not have this issue.

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    [REDACTED]:
        SSORegion: us-east-1
        StartUrl: [REDACTED]
        DefaultRegion: us-east-1
DefaultRegion: us-east-1
ConsoleDuration: 60
CacheRefresh: 168
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
```
