### ISSUE TITLE
Support tags in ListFields

### ISSUE THREAD

**Issue by Moulick** [synfinatic/aws-sso-cli#529]
**Is your feature request related to a problem? Please describe**
Having the tags in `aws-sso list` would be helpful 😄.

**Describe the solution you'd like**
Support Account/Role tags in ListFields

```
AccountName          | AccountAlias | AccountIdPad | Expires | Profile               | RoleName    |  Tags                     
===============================================================================================================================
company-a-production | c-12334-prod | 123456789123 | 59m     | 123456789123:ReadOnly | c-Developer | team:team-a,type:internal
```

**Comment by synfinatic** [comment]
Yeah I've been thinking about this myself.  The thing that I don't have a good handle on is that roles can have lots of tags and I don't want the `list` command to only be useful on 5K wide screen monitors.  How to keep this manageable?  Any thoughts?

**Comment by PacoVK** [comment]
Maybe, make this column optional. The user can decide whether this info is helpful/ useful depending on the amount of tag that are used. 
Another option is to filter tags, eg. you could specify the tag keys to be included in the `config.yml`
WDYT?

**Comment by Moulick** [comment]
We could probably support sprig as in `ProfileFormat` where then the user could define `{{ .Tags.xyz }}`, or only show the tags mentioned in `AccountPrimaryTag` ?

**Comment by synfinatic** [comment]
So is the general consensus that `<name>:<value>` the correct output format? 

@Moulick:  What would `{{ .Tags.xyz }}` output?

**Comment by Moulick** [comment]
I take back `{{ .Tags.xyz}}`, that was a bad suggestion. I am now thinking something like (minimal config)

```yaml
SSOConfig:
  Default:
    Accounts:
      123456789123:
        Name: company-a-production
        Tags:
          team: team-a
          type: internal  

ProfileFormat: "{{ coalesce .AccountName .AccountIdPad }}:{{ .RoleName }}"

AccountPrimaryTag:
  - env

ListFields:
  - AccountName
  - AccountAlias
  - AccountIdPad
  # - Arn
  - Expires
  - Profile
  - RoleName
  - Tags
    - team
    - type
```

will produce 

```

AccountName          | AccountAlias | AccountIdPad | Expires | Profile               | RoleName    |  Tags                     
===============================================================================================================================
company-a-production | c-12334-prod | 123456789123 | 59m     | 123456789123:ReadOnly | c-Developer | team:team-a, type:internal
```
