### ISSUE TITLE
AccountAlias is always AccountName

### ISSUE THREAD

**Issue by PacoVK** [synfinatic/aws-sso-cli#534]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.11.0 -- Copyright 2021-2022 Aaron Turner
ea15d31f496ce9e7c13bb76c562a738748bfac47 (v1.11.0) built at 2023-08-03T02:44:01+0000
```

**Describe the bug:**
Although the docs state that you can use AccountAlias as part of the profile name, as well as this is a column in the `aws-sso list` output the AccountAlias is not fetched and instead the AccountName is displayed. 

**To Reproduce:**
 1. Set AccountAlias of an AWS Account to something different that the AccountName (AccountName=Foo AccountAlias=bar)
 2. Set `ProfileFormat: '{{ .AccountAlias }}:{{ .RoleName }}'` in your `~/.aws-sso/config.yaml`
 3. Update aws-sso cache with `aws-sso cache`
 4. Run `aws-sso config-profiles` or `aws-sso list` to see the result

**Expected behavior:**
AccountAlias is set to `bar`. Hence, the profile would be something like `bar:my-role`

**Actual behaviour:**
AccountAlias is still set to `Foo`. The profile is something like `Foo:my-role`.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.5

**Additional context:**
Seems like the [method](https://github.com/search?q=repo%3Asynfinatic%2Faws-sso-cli%20GetAccountAlias()&type=code) `getAccountAlias()` is there but not used anywhere.
Instead the AccountAlias is [explicitly set](https://github.com/synfinatic/aws-sso-cli/blob/25b4e090b8f95fcccb4b89c52609e20e180aff8d/sso/cache.go#L482) to AccountName 

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    foo:
        SSORegion: eu-central-1
        StartUrl: https://bar.awsapps.com/start
        DefaultRegion: eu-central-1
DefaultRegion: eu-central-1
ConsoleDuration: 60
CacheRefresh: 8
AutoConfigCheck: true
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: '{{ .AccountAlias }}:{{ .RoleName }}'
```
