### ISSUE TITLE
New config is generating maxretry/maxbackoff = 0

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/aws-sso-cli#536]
**Output of `aws-sso version`:**
```
Example output:
AWS SSO CLI Version 1.12.0 -- Copyright 2021 Aaron Turner
```

**Describe the bug:**

Users running `aws-sso config` end up with invalid values:

```yaml
SSOConfig:
  Default:
    SSORegion: us-east-1
    StartUrl: https://foo.awsapps.com/start
    maxbackoff: 0
    maxretry: 0   
```
