### ISSUE TITLE
Generated profile names contain whitespaces

### ISSUE THREAD

**Issue by PacoVK** [synfinatic/aws-sso-cli#552]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.11.0 -- Copyright 2021-2022 Aaron Turner
ea15d31f496ce9e7c13bb76c562a738748bfac47 (v1.11.0) built at 2023-08-03T02:44:01+0000
```

**Describe the bug:**
If you set `ProfileFormat: '{{ .AccountAlias }}:{{ .RoleName }}'` in your `~/.aws-sso/config.yaml` and the AccountName of the AWS Account is eg. set to "My Account" the profile may be generated like
```
[profile My Account:ReadOnly]
credential_process = /opt/homebrew/bin/aws-sso -u open -S "foo" process --arn arn:aws:iam::12
345678912:role/ReadOnly
region = eu-central-1
```
According [the docs](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html) named profiles don't allow spaces 

**To Reproduce:**
 1. Create AWS Account and set the AccountName to "My Account" (mind the space)
 2. set `ProfileFormat: '{{ .AccountAlias }}:{{ .RoleName }}'` in your `~/.aws-sso/config.yaml`
 3. Let `aws-sso` generate your `~/.aws/config` file
 4. You won't be able to use the resulting named profile eg. with the `aws-cli` [profile My Account:MyRole]` because of the whitespace

**Expected behavior:**
Saces are replaced by something valid, eg. "-"

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.5

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    foo:
        SSORegion: eu-central-1
        StartUrl: https://bar.awsapps.com/start
        DefaultRegion: eu-central-1
DefaultRegion: eu-central-1
ConsoleDuration: 60
CacheRefresh: 8
AutoConfigCheck: true
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: '{{ .AccountAlias }}:{{ .RoleName }}'
```
