### ISSUE TITLE
user_code is not displayed anywhere during login, but needs to be verified

### ISSUE THREAD

**Issue by PacoVK** [synfinatic/aws-sso-cli#572]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.13.1 -- Copyright 2021-2023 Aaron Turner
7c08e58ad2a2c941bfa42ad98b0429f3fefa1ca7 (v1.13.1) built at 2023-08-28T23:00:04+0000
```

**Describe the bug:**
I am asked to verify a code, but the code does not show up anywhere, so i cannot verify

**To Reproduce:**
 1. Logout from sessions `aws-sso logout`
 2. Login again via aws-sso-cli
 3. AWS asks me to verify a code

**Expected behavior:**
I get the code for verification displayed in my CLI. Currently only if i set `AuthUrlAction: <print | clip>` (as part of the URL)

**Screenshots:**
![image](https://github.com/synfinatic/aws-sso-cli/assets/27785614/9365f99c-a953-42a9-abb4-fa79f4e2d383)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.5.2 

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    foo:
        SSORegion: eu-central-1
        StartUrl: https://<redacted>.awsapps.com/start
        DefaultRegion: eu-central-1
DefaultRegion: eu-central-1
ConsoleDuration: 60
CacheRefresh: 8
AutoConfigCheck: true
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 0
HistoryMinutes: 1440
ProfileFormat: '{{ StringReplace " " "-" .AccountAlias }}:{{ .RoleName }}'
```
