### ISSUE TITLE
Allow account name to be used when aws-sso exec <account-name>

### ISSUE THREAD

**Issue by Gavin89** [synfinatic/aws-sso-cli#614]
**Is your feature request related to a problem? Please describe.**
Hi, as part of our stack we spin up many accounts, and we already know what our account name will be eg tmp-gh101, currently, I have to run aws-sso list to find the new account ID, to then run aws-sso exec -A <id>.

**Describe the solution you'd like**
I would like to have an extra param to exec using account name, rather than ID.

aws-sso exec -a tmp-gh101 -R AdminAccess

**Comment by synfinatic** [comment]
Have you considered using `--profile` and setting  `ProfileFormat: '{{ FirstItem .AccountName (nospace .AccountAlias) }}:{{ .RoleName }}'`?

Would do what you need I think.

**Comment by Gavin89** [comment]
Would using --profile assume that it is already in my ~/.aws/config? As these are temp envs that we spin up and down a lot we dont add profiles

**Comment by synfinatic** [comment]
You can use `--profile` today on the CLI, just that it defaults to the `<AccountID>:<RoleName>`.  The `ProfileFormat` I provided (which I copied from the FAQ) uses the Account Name in place of the ID.

`aws-sso` can manage your profiles in `~/.aws/config` via the `config-profiles` command and it will use the same `ProfileFormat` to name them, but that isn't necessary for `--profile` on the CLI with the `exec` command.

**Comment by Gavin89** [comment]
I added that and it still didnt work 

```
❯ cat ~/.aws-sso/config.yaml
SSOConfig:
    <company>:
        SSORegion: us-west-2
        StartUrl: https://d-<redacted>.awsapps.com/start
ConsoleDuration: 720
CacheRefresh: 168
UrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
FullTextSearch: true
ProfileFormat: '{{ FirstItem .AccountName (nospace .AccountAlias) }}:{{ .RoleName }}'
```
