### ISSUE TITLE
Invalid character '<' error when running aws-sso console against China AWS SSO

### ISSUE THREAD

**Issue by deanmax** [synfinatic/aws-sso-cli#634]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.13.1 -- Copyright 2021-2023 Aaron Turner
7c08e58ad2a2c941bfa42ad98b0429f3fefa1ca7 (v1.13.1) built at 2023-08-28T23:03:47+0000
```

**Describe the bug:**
```
❯ aws-sso --sso=china console --account=1122334455 --role=CHINA-DEVOPS --duration=720
INFO    Opening URL in: default browser
INFO    Waiting for SSO authentication...
FATAL   Error running command: Error parsing Login response: invalid character '<' looking for beginning of value 
```
If it's first time login, an Authorization Request browser window will pop up correctly
<img width="698" alt="Screenshot 2023-10-18 at 11 53 23" src="https://github.com/synfinatic/aws-sso-cli/assets/3320547/db4f02f8-0f9f-46a0-96e5-8f10d1db911f">
However after you click "Allow", you'll see the above error in the terminal.

`aws-sso --sso=default console --account=1122334455 --role=sso-devops -duration=720` works fine
`aws-sso --sso=china eval --account=1122334455 --role=CHINA-DEVOPS` works fine

**To Reproduce:**
 1. Setup `~/.aws-sso/config.yaml` as described
 2. Run `aws-sso --sso=china console --account=1122334455 --role=CHINA-DEVOPS --duration=720`.

**Expected behavior:**
AWS console browser window popped up after running `aws-sso` console command

**Screenshots:**

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Version 13.5

**Additional context:**

**Contents of `~/.aws-sso/config.yaml`:**
```
  SSOConfig:
    china:
      SSORegion: cn-north-1
      StartUrl: https://start.home.awsapps.cn/directory/xxx-sso (redacted)
      DefaultRegion: cn-north-1
    default:
      SSORegion: us-west-2
      StartUrl: https://xxxsso.awsapps.com/start
      DefaultRegion: us-west-2
  DefaultSSO: default
  UrlAction: open
  LogLevel: info
  HistoryLimit: 10
  HistoryMinutes: 1440
```
