### ISSUE TITLE
Even when the computer is in sleep mode, SSO sessions can expire and result in multiple session requests being opened in the browser

### ISSUE THREAD

**Issue by yasithab** [synfinatic/aws-sso-cli#644]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.14.2 -- Copyright 2021-2023 Aaron Turner
792f11ec86a5ce6683ba2df7cb544e4f76f2431b (v1.14.2) built at 2023-10-20T04:29:15+0000
```

**Describe the bug:**
Even when the computer is in sleep mode, SSO sessions can expire and result in multiple session requests being opened in the browser. For instance, if the computer is asleep for 12 hours, there may be more than 10 session requests visible in the browser (refer to the attached screenshot). How can I avoid this? Is there a command to open the browser only when I specifically want to refresh the token?

**To Reproduce:**
Computer is in sleep mode and SSO session expired.

**Expected behavior:**
The desired behavior is to have the browser open only when the computer wakes up
OR 
When a specific command is executed to refresh the token. For instance, in the morning before starting work, running a command will open the browser and allow for token refreshing.

**Screenshots:**
<img width="1728" alt="1" src="https://github.com/synfinatic/aws-sso-cli/assets/9078175/ba91092e-323c-4dfb-b68a-4e0e2e1ce33c">

**Desktop**
 - OS: macOS
 - Version 14.0 (23A344)

**Additional context:**
N/A

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    PF:
        SSORegion: us-east-1
        StartUrl: https://d-0123456789.awsapps.com/start
        DefaultRegion: ap-southeast-1
DefaultRegion: ap-southeast-1
ConsoleDuration: 720
CacheRefresh: 168
AutoConfigCheck: true
UrlAction: granted-containers
ConfigProfilesUrlAction: granted-containers
UrlExecCommand:
    - /Applications/Firefox.app/Contents/MacOS/firefox
    - "%s"
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ .AccountIdPad }}:{{ .RoleName }}"
FullTextSearch: true
```
