### ISSUE TITLE
Unable to use in GitHub Codespaces

### ISSUE THREAD

**Issue by Moulick** [synfinatic/aws-sso-cli#816]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.14.3 -- Copyright 2021-2023 Aaron Turner
f1574cff0d18ccb6edebe73383e389eae011b659 (v1.14.3) built at 2024-01-15T22:27:44+0000
```

**Describe the bug:**
Trying to use aws-sso-cli in github codespaces. Trying to authenticate give the above error. `aws configure sso` opens a new tab/popup to click the allow access button.

**To Reproduce:**
1. Launch a new Github Codespace
1. Install `aws-sso-cli`
1. Run `aws-sso list` and go through the wizard
1. See error below

**Expected behaviour:**
Open AWS login page to authorise

**Current behaviour**
```shell
@Moulick ➜ ~ $ aws-sso
Enter passphrase to unlock "/home/codespace/.aws-sso/secure": 

        Verify this code in your browser: XZST-WNRZ
FATAL   Unable to authenticate                        error="Unable to open URL with default browser: exec: \"xdg-open\": executable file not found in $PATH"
@Moulick ➜ ~ $ 
```

**Desktop (please complete the following information):**
 - Github Codespaces

**Contents of `~/.aws-sso/config.yaml`:**

```yaml
SSOConfig:
    Default:
        SSORegion: eu-central-1
        StartUrl: https://dummy.awsapps.com/start
ConsoleDuration: 720
CacheRefresh: 168
UrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ FirstItem .AccountName (.AccountAlias | nospace) }}:{{ .RoleName }}"
FullTextSearch: true
```

**Comment by Moulick** [comment]
It seems there is a `$BROWSER` variable exported in Github Codespaces which is some script that handles URL opening nicely.

**Comment by synfinatic** [comment]
`aws-sso` knows nothing about the $BROWSER variable.  Since you don't have `xdg-open`, you'll want to configure the browser manually per the docs: https://synfinatic.github.io/aws-sso-cli/config/#browser-urlaction-urlexeccommand

**Comment by Moulick** [comment]
Oh nice. Tried this now and got the following issue

```yaml
UrlAction: exec
UrlExecCommand:
    - $BROWSER
    - "%s"
```

```shell
@Moulick ➜ ~ $ aws-sso list
WARNING The specified item could not be found in the keyring 
Enter passphrase to unlock "/home/codespace/.aws-sso/secure": 

        Verify this code in your browser: <redacted>
FATAL   Unable to authenticate                        error="Unable to exec `$BROWSER https://device.sso.eu-central-1.amazonaws.com/?user_code=<redacted>`: exec: \"$BROWSER\": executable file not found in $PATH"
```
