### ISSUE TITLE
aws-sso-profile returns error

### ISSUE THREAD

**Issue by derkrisz** [synfinatic/aws-sso-cli#836]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.15.0 -- Copyright 2021-2023 Aaron Turner
9f897c5be301ea1a3cd1b143dc75d0d2bff5e500 (v1.15.0) built at 2024-04-05T18:29:16+0000
```

**Describe the bug:**
Running `aws-sso-profile` returns the following error:
`FATAL   Error running command: Please specify --refresh, --clear, --arn, or --account and --role`

**To Reproduce:**
 1. `aws-sso-profile`

**Expected behavior:**
A list of available profiles returned

**Screenshots:**
-

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Sonoma 14.4.1

**Additional context:**
I have no problem using `aws-sso exec` or `config-profiles`. I'm using `zsh` shell and enabled autocompletion.

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    Default:
        SSORegion: us-east-1
        StartUrl: xxx
        AuthUrlAction: open
DefaultSSO: Default
DefaultRegion: us-east-1
ConsoleDuration: 720
CacheRefresh: 168
Threads: 5
MaxBackoff: 5
MaxRetry: 10
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ FirstItem .AccountName (.AccountAlias | nospace) }}:{{ .RoleName }}"
AccountPrimaryTag:
    - AccountName
    - AccountAlias
    - Email
PromptColors:
    descriptionbgcolor: Turquoise
    descriptiontextcolor: Black
    inputbgcolor: DefaultColor
    inputtextcolor: DefaultColor
    prefixbackgroundcolor: DefaultColor
    prefixtextcolor: Blue
    previewsuggestionbgcolor: DefaultColor
    previewsuggestiontextcolor: Green
    scrollbarbgcolor: Cyan
    scrollbarthumbcolor: LightGrey
    selecteddescriptionbgcolor: DarkGray
    selecteddescriptiontextcolor: White
    selectedsuggestionbgcolor: DarkGray
    selectedsuggestiontextcolor: White
    suggestionbgcolor: Cyan
    suggestiontextcolor: White
ListFields:
    - AccountIdPad
    - AccountAlias
    - RoleName
    - Profile
    - Expires
FullTextSearch: true
```
